/**
 * روم‌کیت UI — Spartan UI (helm) components.
 *
 * Components are generated by `nx g @spartan-ng/cli:ui --name=<x>` and live in
 * their own entrypoint, so import from the specific one rather than here:
 *
 *   import { HlmButton } from '@org/ui-components/button';
 *   import { HlmInput }  from '@org/ui-components/input';
 *
 * Theming: helm reads the shadcn variable contract (--primary, --background,
 * --border, …), which `apps/web/src/styles.scss` maps onto the Luminous Glass
 * tokens — so these components inherit the brand with no local overrides.
 */
export {};
